[default]
solc = '0.8.9'
via_ir = true
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
test = 'test/foundry'
cache_path  = 'foundry-cache'
remappings = [
    'ds-test=lib/ds-test/src/',
    'forge-std=lib/forge-std/src/',
]
fuzz_runs = 5000
fuzz_max_global_rejects = 2_000_000
optimizer_runs = 19_066

[test]
via_ir = false
src = 'test/foundry'
